### ISSUE TITLE
express + webpack-hot-middleware: No effect on file changes

### ISSUE THREAD

**Issue by Toilal** [Angelinsky7/Docker-Volume-Watcher#1]
I try to migrate some dockerized development environments from a home made vagrant VM to Docker for Windows, but I hit the file notification issue, so i'm trying this project.

Sadly, I can't make it work, it seems to have no effect. When I change sources files, it doesn't trigger a TypeScript rebuild.

My developpement environment is based on express and webpack-hot-middleware. Any idea ?

**Comment by Angelinsky7** [comment]
Do you thing you could send me your docker "project" (without the source) so i could test it and understand what is the issue ?
And your docker version, window version and any other informations that could narrow the issue :-)

**Comment by Angelinsky7** [comment]
I tried to build this example : https://github.com/glenjamin/webpack-hot-middleware/tree/master/example

can you try with this project ? [test#1.zip](https://github.com/Angelinsky7/Docker-Volume-Watcher/files/1239508/test.1.zip)
install the dependencies with `docker-compose.exe run --rm app npm install`
run it with `docker-compose.exe run --rm  --service-ports app npm start`

on my system, it's working and if you look into the window events you should find a "Docker Volume Watcher" eventlog that should tell you something like that
```
Monitor started
Watcher create for D:\Projects/docker/test#1/src
Add container f3829add5e008cc12394d333cf44695a0d29ef14016e788c246c89c5c80a7c56 : 1 notifier(s)
```

**Comment by Angelinsky7** [comment]
@Toilal no news from you, can is close ?

**Comment by Angelinsky7** [comment]
closed because not responding
