### ISSUE TITLE
need compiled binary 

### ISSUE THREAD

**Issue by shoks** [Angelinsky7/Docker-Volume-Watcher#10]
hi i compiled the service and the trayapp but was unable to run it due to several occuring bugs is there any binary of this hosted somewhere?

**Comment by Angelinsky7** [comment]
yes there : https://github.com/Angelinsky7/Docker-Volume-Watcher/releases
the latest build : https://github.com/Angelinsky7/Docker-Volume-Watcher/releases/download/0.0.11.0/ch.darkink.docker_volume_watcher.msi

which bug ? could you give the build log ?

**Comment by shoks** [comment]
thank you!

**Comment by shoks** [comment]
ill send you the build log

**Comment by Angelinsky7** [comment]
i'm closing for now, when you'll come back with log and etc we'll reopen
