### ISSUE TITLE
More details please

### ISSUE THREAD

**Issue by alexgorbatchev** [Angelinsky7/Docker-Volume-Watcher#6]
Could you please add more details to the readme?

Specifically, I installed the service, but I don't see any effect... restarted my containers, still no visible effect. How do I tell if something is wrong or if it's working at all? Is there a step after installation?

**Comment by alexgorbatchev** [comment]
I found in the windows services list that it's set to `Manual` start. Tried starting it and it gives me this dialog:

![image](https://user-images.githubusercontent.com/65633/30771218-d54a8fda-9ff6-11e7-8bfd-d498974f641b.png)

**Comment by alexgorbatchev** [comment]
```
$ NET START "Docker Volume Watcher"
The Docker Volume Watcher service is starting.
The Docker Volume Watcher service could not be started.

The service did not report an error.

More help is available by typing NET HELPMSG 3534.
```

**Comment by Angelinsky7** [comment]
After installing the msi you should have an icon on the desktop (and in the menu).
If you start it an application should start and appears in the tray (near the clock)

![image](https://user-images.githubusercontent.com/13157968/30781808-16cbd63c-a126-11e7-8166-5148d410933f.png)

with the right click you should access to the menu 

![image](https://user-images.githubusercontent.com/13157968/30781814-346116e4-a126-11e7-84af-c9f4e82d4682.png)

and in settings you can configure the service

![image](https://user-images.githubusercontent.com/13157968/30781817-4e025d74-a126-11e7-8d5e-68f0ac32623b.png)

if at the bottom left of the window there is a green circle saying : service is running it sould work.
you can also check into window event manager : into Applications and service log -> Docker Volume Watcher.
You should see something like that :

1. Service starting - v0.0.7.0, with polling interval as 1000ms and mandatory ignore file : True
2. Monitor started

Then if you open a container :

1. Watcher create for SRC_PATH
2. Add container 0b5be060ad262b19f2320d20b63076592ebb7f31b6d73452515c9da6d8918c09 : 1 notifier(s)
3. File has changed : Changed - SRC_PATH\FILE - DEST_PATH\FILE
4. Notify SRC_PATH\FILE mapped to DEST_PATH has changed into 0b5be060ad262b19f2320d20b63076592ebb7f31b6d73452515c9da6d8918c09

Then finally :

1. Remove container 0b5be060ad262b19f2320d20b63076592ebb7f31b6d73452515c9da6d8918c09

Is this enought explanation ?

But you totally right, the readme need work.

**Comment by Angelinsky7** [comment]
i should add this :

![image](https://user-images.githubusercontent.com/13157968/30781944-e8d24f42-a128-11e7-8bd9-cedbbec06cca.png)

The polling settings : speed at which the service will poll the docker server for containers
The ignore file : only watch container that have an ignore file at the root of the source path

**Comment by Angelinsky7** [comment]
The readme is a little better now but i would greatly appreciate comments to improve it

**Comment by alexgorbatchev** [comment]
This is great, i got it all to work! Didn't even have to restart my watching container :)

**Comment by Angelinsky7** [comment]
this is closed then...
thanks
